version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8090
    volumes:
      - .:/app
    ports:
      - "8090:8090"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: tses
      POSTGRES_USER: tses
      POSTGRES_PASSWORD: tses
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data:
  redis_data:
